adding jolokia module

diff --git a/shellstatd b/shellstatd
--- a/shellstatd
+++ b/shellstatd
@@ -1,33 +1,51 @@
 #!/bin/bash
 
 ACTION=$1
-if [ "$ACTION" == "" ]
-then
-   echo "Usage:  shellstatd start | stop | restart"
+if [ "$ACTION" == "" ] then
+   echo "Usage:  "
+   echo "shellstatd start | stop | restart"
+   echo .
+   echo "Options:"
+   echo "-c    Configuration File Location"
+   echo .
    exit 1
 fi
 
-if [ -f "/etc/shellstatd.conf" ]
-then
-   CONFIG_FILE="/etc/shellstatd.conf"
-fi
-if [ -f "./shellstatd.conf" ]
-then
-   CONFIG_FILE="./shellstatd.conf"
+while getopts :c option 
+do 
+   case "${option}" in 
+      c) CONFIG_FILE=${OPTARG};; 
+      ?) ERROR=${OPTARG};;
+   esac
+   if [ "$ERROR" == "" ] then
+      echo "Not a valid option: $ERROR"
+      exit 1
+   if
+done
+
+if [ -f "$CONFIG_FILE" ] then
+   echo "Using configuration file: $CONFIG_FILE"
+else
+   if [ -f "/etc/shellstatd.conf" ] then
+      CONFIG_FILE="/etc/shellstatd.conf"
+   else
+      if [ -f "./shellstatd.conf" ] then
+         CONFIG_FILE="./shellstatd.conf"
+      fi
+   fi
 fi
 
-if [ ! -f "$CONFIG_FILE" ]
-then
+if [ ! -f "$CONFIG_FILE" ] then
    echo "FATAL: config file '$CONFIG_FILE' not found."
    exit 1
 fi
+
 . $CONFIG_FILE
 
 
 function start() {
    # check for previously running shellstatd
-   if [ -f "$PID_FILE" ]
-   then
+   if [ -f "$PID_FILE" ] then
       echo "shellstatd was already running.  No action taken."
       exit 1
    fi 
@@ -46,8 +64,7 @@ function start() {
 
 function stop() {
    # Be sure shellstatd is running
-   if [ ! -f "$PID_FILE" ]
-   then
+   if [ ! -f "$PID_FILE" ] then
       echo "shellstatd was not running.  No action taken."
       exit 1
    fi
@@ -61,18 +78,15 @@ function stop() {
 
 
 
-if [ "$ACTION" == "start" ]
-then
+if [ "$ACTION" == "start" ] then
    start
 fi
 
-if [ "$ACTION" == "stop" ]
-then
+if [ "$ACTION" == "stop" ] then
    stop
 fi
 
-if [ $ACTION == "restart" ]
-then
+if [ $ACTION == "restart" ] then
    stop
    start
 fi
